# Sungpil Han added: start ----

baseURL = "http://shanmdphd.rbind.io/"
title = "Sungpil Han, M.D/Ph.D"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disqusShortname = "hugoshanmdphd"

# Sungpil Han added: end ----

languageCode = "en-us"
theme = "shan-xmin"
googleAnalytics = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tips"
    url = "/tips/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    since = "2016"
    keywords = ["Sungpil Han", "Clinical Pharmacology","Medicine"]
    description = "Sungpil Han's Blog. A website built through Hugo and blogdown using xmin theme."
    footer = "&copy; [Sungpil Han](./) 2017 | [Github](https://github.com/shanmdphd) | [Twitter](https://twitter.com/shanmdphd)"
    GithubEdit = "https://github.com/rbind/shanmdphd.rbind.io/edit/master/content/"
