---
slug: broom
title: broom 패키지
date: 2017-10-18
author: null
categories: [Data Science]
tags: [broom, data science]
output:
  blogdown::html_page:
    df_print: kable
#editor_options: 
#  chunk_output_type: console
---

`broom` 패키지를 사용하면 통계 분석을 `data.frame` 내에서 할 수 있어서 후속 작업에 큰 잇점이 있습니다. 
<https://cran.r-project.org/web/packages/broom/vignettes/broom.html>

```{r, message=FALSE}
# packages
library(tidyverse)
library(broom)
library(beginr) 
```

# 예제

다룰 데이타는 `dataset::mtcars`입니다. 기술통계값은 다음과 같습니다.

```{r}
head(mtcars)
broom::tidy(mtcars)
```

차의 중량과 연비와의 관계를 그림으로 그리면 다음과 같습니다. 

```{r}
beginr::plotlm(x = mtcars$wt, y = mtcars$mpg, xlab = 'wt', ylab = 'mpg', plot.title = 'mtcars')
```



```{r}
p <- ggplot(mtcars, aes(wt, mpg, label = rownames(mtcars))) 

p + 
  geom_point() +
  geom_text(vjust = 0, nudge_y = 0.5) +
  geom_text(aes(label = paste0(wt, "^(", mpg, ")")), parse = TRUE)
```




```{r}
lmfit <- stats::lm(formula = mpg ~ wt, data = mtcars)
lmfit

summary(lmfit)
broom::tidy(lmfit)
broom::augment(lmfit)
broom::glance(lmfit)
``` 

# Reference

- `r format(citation('broom'), style = 'text')`

